# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 1.0
# If the value is 0~1,023, it means the load works to the CCW direction. If the value is 1,024~2,047, it means the load works to the CW direction
top_box:
  ID: 7
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  #Moving_Speed: 300

